### ISSUE TITLE
White Paper Redirect

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#14]
The correct white paper is located here: https://github.com/digitalcredentials/dcc-website/blob/master/docs/white-paper-building-digital-credential-infrastructure-future.pdf

On the Jekyll site, please redirect https://github.com/digitalcredentials/dcc-website/tree/master/wp-content/uploads/2020/02 to https://github.com/digitalcredentials/dcc-website/blob/master/docs/white-paper-building-digital-credential-infrastructure-future.pdf

This is an example of a Jekyll library that does redirects: https://github.com/jekyll/jekyll-redirect-from

**Comment by fields37** [comment]
Hmm, it doesn't seem that the jekyll-redirect-from library can handle resource requests that are not webpage URLs, i.e. a link to a pdf.

**Comment by bmuramatsu** [comment]
Can you do a custom 404 to redirect a specific link (to a PDF) to another
PDF or generated page?

Redirect wordpress...pdf to correct pdf.

Or

Redirect wordpress...pdf to the homepage or publications page?

**Comment by fields37** [comment]
In order for the 404 page to continue functioning with images and styles loading, when the site URL is changed the base href in line https://github.com/digitalcredentials/dcc-website-jekyll/blob/8785d18ef389720c65d4d8641150c5fa37f1b07b/_layouts/default.html#L7 will need to be edited to reflect the new page URL.

And for the redirects to work, when the page is moved to a custom domain from the Github pages format, pathSegmentsToKeep in line https://github.com/digitalcredentials/dcc-website-jekyll/blob/8785d18ef389720c65d4d8641150c5fa37f1b07b/js/redirect.js#L5 will need to be changed to 0 to reflect the additional subdomain that exists in the URL of a github pgaes site.

**Comment by fields37** [comment]
To do: close this issue and put the instructions in the above comment into a "Launch checklist" issue

**Comment by kayaelle** [comment]
@fields37 - leaving this issue open in prep for launch
