### ISSUE TITLE
Lower resolution of background source images so they load faster

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/dcc-website#19]

**Comment by bmuramatsu** [comment]
For the binary image, you could probably also make it 20-25% its current
height. It's probably bigger than we need.

**Comment by fields37** [comment]
I realized the header image on the homepage was a png file, switching it to jpg reduced the size from ~3.5mb to 500kb. https://github.com/digitalcredentials/dcc-website-jekyll/commit/eafdf01084f7d7a8a8c86b1679f71c93a43ccd3e

**Comment by bmuramatsu** [comment]
I also suggest reducing the height of the image to something on the order of the same height as the top nav bar. At it's current height, over half of the height of the page on screen is lost to chrome meaning that less than 50% what an individual sees is content.

**Comment by bmuramatsu** [comment]
When the image at the top of each page just contains the page title, I'd
make it much shorter. If it includes text then it should be big enough to
give breathing room / whitespace. I'm ok with that block changing height as
appropriate.

**Comment by fields37** [comment]
Alright, I'll make some global adjustments to spacing based on this feedback. I honestly think a lot of the larger type could also be reduced a bit in size, I'll review that as well.

**Comment by bmuramatsu** [comment]
Great, thanks!

**Comment by fields37** [comment]
I made some of these size reductions to the header sections in commit https://github.com/digitalcredentials/dcc-website-jekyll/commit/e3ca36eb55687238b7ea5576fcab26ea94231dea, let me know if you would like things even smaller.

**Comment by bmuramatsu** [comment]
Please reduce it further. The header with the page title isn't the most
important thing on the page, the content below it is.

My starting point would be the following, and I think it could be smaller
still.

[image: Screen Shot 2023-04-19 at 9.45.39 AM.png]
