### ISSUE TITLE
Current site thank you page is missing

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#20]
404 error for contact form submission thank you:

https://digitalcredentials.mit.edu/thankyou

We should fix this -- @bmuramatsu what should the content be on this page? Let us know know below and we'll add it.

@fields37 And then make sure it is working on the new site - do you need an new issue for the new site?

**Comment by bmuramatsu** [comment]
Unfortunately this isn't my page. It hasn't ever existed. It's a mailchimp
configuration thing which is Gillian. I'm asking her to look at it.

Brandon

**Comment by kayaelle** [comment]
Thanks @bmuramatsu

**Comment by kayaelle** [comment]
@gwalsh311, when I tested, I didn't get a 404 but it just redirected back to the site with no confirmation. 

Is there a field in mailchimp settings where you enter a url for the thank you page?

**Comment by bmuramatsu** [comment]
I believe I saw that there's a mailchimp thank you page after I made my
suggestion to redirect to our homepage, that's probably the least intrusive
way to accomplish things.

**Comment by kayaelle** [comment]
It works for now and definitely better than a 404. As a user I was confused when it went back to the homepage. Since the new site will have multiple pages, how about we add one more that serves as the thank you page and reads:

Thanks for signing up for the DCC Mailing List

And then we can update mailchimp after the new site is launched.

**Comment by kayaelle** [comment]
This looks good. Thanks, Gillian!
