### ISSUE TITLE
Get Involved Page

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/dcc-website#21]
A new page for the top level nav. Suggest at the far right of the top nav (i.e., last item).

[Suggested text in a Google Doc](https://docs.google.com/document/d/1-7hDeFaHPONXziae17e0-M51vn3gfLWF1etL6JlsyGk/edit#heading=h.u58dkmh2smh4).

(Top third of the doc).

**Comment by fields37** [comment]
I've added the content [here](https://digitalcredentials.github.io/dcc-website-jekyll/get-involved), although I haven't made any styling changes yet. I plan to add a little more space between the section headers and the previous sections, and reduce the size of the call to action.
