### ISSUE TITLE
Membership Page

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/dcc-website#22]
(Technically a sub-page of Get Involved but I think it's fine to put at the same level as the other pages for a completely flat hierarchy.)

[Suggested text in a Google Doc](https://docs.google.com/document/d/1-7hDeFaHPONXziae17e0-M51vn3gfLWF1etL6JlsyGk/edit#heading=h.i5rg80ewl2mm).

(Middle third of the doc).

**Comment by fields37** [comment]
[Here's](https://digitalcredentials.github.io/dcc-website-jekyll/membership) a first rev of the membership page. I used diamonds for the bullets, but if you have a preferred character I can swap it in. I also created a smaller inline version of the call to action from the homepage to use as the interspersed signup button.

**Comment by bmuramatsu** [comment]
- I think the call to action can be shorter / less prominent
   - Can you please add padding / space after paragraphs to improve
   legibility
   - Can you please add padding around the table as requested, I suggested
   the table should be about 80% width of the screen
   - Can you please center the text in the General Public, Member and Core
   Member columns
   - Can you please make sure that the last updated text reads as a
   different line, including italicize it

**Comment by fields37** [comment]
Additionally:
- [ ] Change 'X' to checkmark in table
- [ ] Make table header sticky to top of screen
- [ ] Make "last updated" smaller

**Comment by fields37** [comment]
Sticky table header done in https://github.com/digitalcredentials/dcc-website-jekyll/pull/2/commits/65603e010cd9a091bacdf3308dd7248e8a2467e0
