### ISSUE TITLE
Site Navbar

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/dcc-website#23]
Work out responsive navbar that doesn't wrap page titles, given the longer list of pages now on the site.

@bmuramatsu Are these the page titles and ordering you want for the new sections?
<img width="1333" alt="Screen Shot 2023-04-17 at 3 26 07 PM" src="https://user-images.githubusercontent.com/20584379/232590695-823b49d0-91d6-49a3-8ac3-a53a63ca8846.png">

**Comment by fields37** [comment]
Hi @bmuramatsu, I'm a bit unsure of how you want the website structured. Are you saying you want Technology and Projects combined into a single page? Wolud that be filled with the content headed "What We Do" in [this google doc](https://docs.google.com/document/d/1N6noeCAd-Q3mAfNen7V7iN8B8F9BpcrPhQODriWmaJM/edit#)? And do you want "Get Involved" and "Membership" combined into a single page, or have Membership listed as a subpage of Get Involved?

**Comment by kayaelle** [comment]
We're going to refer to the google doc. @fields37 will make issues as he needs them for his workflow.
