### ISSUE TITLE
Site Content

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/dcc-website#24]
Copy page structure and content from [google doc, double check it all](https://docs.google.com/document/d/1eetoXrXz9MCixj43CUZ_cF4v6SrKo-85ul4GlRT-Bws/edit?usp=sharing)

**Comment by gwalsh311** [comment]
@fields37 a few quick things: Our Work > LER Ecosystem Map >  --- include a hyperlink for NationSwell (https://nationswell.com/)

**Comment by gwalsh311** [comment]
@fields37 Who We Are > Members > ---- replace "o" with "ó" for Tecnológico de Monterrey

**Comment by fields37** [comment]
Missing accent in Members added in https://github.com/digitalcredentials/dcc-website-jekyll/pull/7/commits/5a8b11aa8933eb0c0b81b719c4f546c7e26ec8d0

**Comment by fields37** [comment]
@gwalsh311 Where do you want the hyperlink in Our Work added, were you thinking on the "Ecosystem Map" heading?

**Comment by gwalsh311** [comment]
> @gwalsh311 Where do you want the hyperlink in Our Work added, were you thinking on the "Ecosystem Map" heading?

No I mean include a link to the NationSwell website where we reference them

**Comment by fields37** [comment]
Ah I got you, sorry for the confusion. Completed in https://github.com/digitalcredentials/dcc-website-jekyll/pull/7/commits/ce7924e9329332d9133bc54c3aa869ad180913a6
