### ISSUE TITLE
Call to Action Block

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/dcc-website#25]
Standardize "Call to Action" blocks across site, always being a distinct block with grey background. Adjust sizing based on whether there is a paragraph + button or just a button.

**Comment by fields37** [comment]
Implemented in 23478306589d0f7223b5929fa399539cd5f9096b and 80e21c02f11ac14be314e89248c3b2daf2d5e610

**Comment by kayaelle** [comment]
Thanks @fields37
