### ISSUE TITLE
Navbar Overhaul

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/dcc-website#26]
- [x] Add hover dropdown to "Who We Are" and "Get Involved", where the top level takes you to the primary page, and the dropdown shows the secondary page option
- [x] Standardize the heights of the navbar at different screen ratios with constants that can be used by the page body, sticky header for tables, etc

**Comment by fields37** [comment]
These updates made in https://github.com/digitalcredentials/dcc-website-jekyll/pull/2, although standardizing the navbar heights wound up being a bit messy. For some reason the margins applied to body don't correspond to the pixel measurements of the rest of the site.

**Comment by kayaelle** [comment]
Thanks @fields37. I'll do some cross-browser testing and if there's anything that needs adjusting will submit a new issue.
