### ISSUE TITLE
Text hierarchy styling tweaks

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/dcc-website#27]
- [x] Change h2 size to 1.75rem, h3 to 1.4rem
- [x] Adjust spacing between them and mobile sizes
- [x] Add a p-small class, use for member bios and "last updated" line below table
- [x] Change member bio headers to both h4

**Comment by fields37** [comment]
Changes made in https://github.com/digitalcredentials/dcc-website-jekyll/pull/3

**Comment by kayaelle** [comment]
Thanks @fields37
