### ISSUE TITLE
Various Bug Fixes

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/dcc-website#28]
- [x] Navbar takes on excessive spacing for some reason below 576px screen width between page titles.
- [x] Membership table is too wide on some mobile screen widths, causing page to scroll horizontally
- [x] Bottom margin on homepage call to action overlaps footer
- [x] Membership table sticky header occasionally phases out while scrolling on mobile - try addressing by arranging z indexes
- [x] Call to action having trouble inserting liquid tag into frontmatter, which means I had to hardcode the contents of the call to action in the "Who We Are" page rather than have it show up at the top like the others. Needs a more elegant solution

**Comment by fields37** [comment]
Addressed top three issues here in https://github.com/digitalcredentials/dcc-website-jekyll/pull/6

**Comment by fields37** [comment]
The sticky header problem seems to not be affected by z indexes, is pretty inconsistent in how it manifests, and seems to show up only on mobile and not on web. Additionally, on mobile the header sometimes awkwardly remains at the top of the screen once you've scrolled past the footer. Needs additional testing on other devices, but I may end up just removing the sticky header or deactivating it on mobile since it's a fairly small problem to spend a lot of time on.

**Comment by kayaelle** [comment]
Hey @fields37 - let's remove the sticky header from mobile.

**Comment by kayaelle** [comment]
@fields37 - I'm not certain what the last checkbox in the list is referencing. Maybe we can find a few mins next week to take a look together.

**Comment by fields37** [comment]
> Hey @fields37 - let's remove the sticky header from mobile.

Implemented in https://github.com/digitalcredentials/dcc-website-jekyll/commit/cc3c7a553d43b029f8b27b77b90c011b37be32ab

**Comment by fields37** [comment]
Call to action issue resolved by changes made in https://github.com/digitalcredentials/dcc-website-jekyll/commit/436e71075d6f4606655a6d8587c66f3ced5daf7a

**Comment by kayaelle** [comment]
Done
