### ISSUE TITLE
Migrate site to Jeckyll

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#3]
Top Nav (should be fixed to the top like the current site): 

DCC Logo (links to landing)

Links:
- Who We Are (/who-we-are.html)
- Technology (/technology.htm)
- Projects (/projects.html)
- Publications (/publications.html)

Footer should remain the same.

Site should pass accessibility testing. Here's an example of browser extensions that will do testing and make recommendations: https://wave.webaim.org/extension/

W3C also provides a conformance checking tool: https://www.w3.org/WAI/test-evaluate/

There are separate issues for landing, who we are, technology, projects, and publications

**Comment by kayaelle** [comment]
Question from @fields37 for @bmuramatsu & @gwalsh311:

For the projects, members, publications, technology sections, will the content under the subheaders be fairly straightforward formatted text, which could include lists, headers, paragraphs, inline images? Is there a desire to have the kind of side by side text/image pairings that we have in the technology section on the current page (image attached), or any other additional fancy formatting?

**Comment by kayaelle** [comment]
I recommended to @fields37 to provide formatting for lists, headers, paragraphs, inline images and also the side text/image. He'll add some demo content.

**Comment by kayaelle** [comment]
Because github pages only run one per repo, @fields37 will put the jekyll version in a separate repo and then will merge it back into this repo when ready for launch. [Jekyll repo](https://github.com/digitalcredentials/demo-dcc-website)

**Comment by bmuramatsu** [comment]
re: styling

- I’d like to see smaller font sizes for primary body text, or more spacing for the headers as on the existing site. (Smaller regular fontsize at 1.1 or 1.2 rem would be easiest and the least change.)
- Yes, it would be good to have a prebuilt style for left aligned and right aligned images.
