### ISSUE TITLE
Resize header on landing page

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#30]
Can we resize the header on the landing page? Make it larger (similar to how it looks on the current site).

**Comment by gwalsh311** [comment]
@fields37 a few comments on the header on landing page

- [ ] (BM) On the homepage, https://digitalcredentials.github.io/dcc-website-jekyll/
Image at the top appears to be lower res and zoomed in. It should also be cropped differently to emphasize a different portion of the image.

- [ ] (ps) Visual design of homepage, top image too dark and too small, links to reports too big 
- [ ] (BM) On sub pages, the chrome (navigation bar and page title) takes up 34% of the screen. I recommend reducing the page title size.

**Comment by bmuramatsu** [comment]
Clarification on the "page title size" I mean the entire div not just the
font size.

**Comment by fields37** [comment]
Done in https://github.com/digitalcredentials/dcc-website-jekyll/commit/f8df1c1932bbf57407190de49f1e662b38229410, let me know if you have any further comments.
