### ISSUE TITLE
Team Page edits

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#31]
- [x] align names to top of photo

- [x] Remove Digital Credentials Consortium from title

- [x] Kerri LinkedIn: https://www.linkedin.com/in/kerrilemoie/

- [x] Change Brandon title (gw will ask him for preferred title)

@fields37

**Comment by fields37** [comment]
Content changes (minus Brandon pending title) completed in https://github.com/digitalcredentials/dcc-website-jekyll/pull/7/commits/6180a0b21a95c8b216ec6db6ef652b29061140ac

Name alignment changed in https://github.com/digitalcredentials/dcc-website-jekyll/pull/7/commits/458602933a6252d4d648d7cfe8cfdd32a17bbd3f. @kayaelle There is still a small margin above the team member name, do you want it completely flush with the top of the image? It currently looks like this: ![Screen Shot 2023-06-06 at 7 34 30 PM](https://github.com/digitalcredentials/dcc-website/assets/20584379/e1110371-bf83-47c8-b82f-c586e18930fc)

**Comment by kayaelle** [comment]
Can we see what it looks like if it is flush to the top of the image so we can compare? Thanks!

**Comment by gwalsh311** [comment]
I like the second one personally

**Comment by kayaelle** [comment]
I like the second one too. 

Also take a look at this part in Phillip's bio: "He serves on the board of **, a degree-completion** college for adult students and was a founding board member of the OpenCourseWare Consortium. He co-authored the ](https://www.collegeunbound.edu/)[Cape Town Open Education Declaration](http://www.capetowndeclaration.org/) and has developed a number of open standards for digital academic credentials including [Mozilla Open Badges (PDF)](https://wiki.mozilla.org/images/5/59/OpenBadges-Working-Paper_012312.pdf)."

Looks like there's a bracket missing after the link for college unbound:  ", a degree-completion"

**Comment by fields37** [comment]
Bracket issue in Philipp's bio fixed in https://github.com/digitalcredentials/dcc-website-jekyll/pull/10/commits/4edc22ec9972b8e6085abf2ffc457264df0ab6bf

**Comment by fields37** [comment]
How does this look to you @kayaelle ? I think it's a bit more balanced than having the top of the text completely aligned with the top of the image, but if you don't like it I'll revert to your recommendation.

<img width="953" alt="Screen Shot 2023-06-12 at 2 23 54 PM" src="https://github.com/digitalcredentials/dcc-website/assets/20584379/eaadfa3a-7d63-4e09-a527-ac06695b42eb">

**Comment by kayaelle** [comment]
@fields37 - this looks good to me. 

re: Brandon's title - it can remain as it is.

@gwalsh311 - if this looks good to you, you can close it. 

Thanks!

**Comment by gwalsh311** [comment]
Closing
