### ISSUE TITLE
Accessibility: Skipped Heading Level 

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#33]
Screen readers may skip a heading if it jumps to h3 if there aren't headings of the previous size before it. 

- [x] As an example. on "Our Work", an h3 is used for "As a learner".  "Our Work" is h1 so "As a learner, should be h2. 

- [x] On the Team page, instead of using h3 for our names, please use a DIV.

- [x] On the Team page, instead of using h4 for our titles, please use a DIV.

- [x] On the Get Involved Page, please use h2 for Community at Large and Institutional members instead of h3.

**Comment by fields37** [comment]
Completed in https://github.com/digitalcredentials/dcc-website-jekyll/pull/10/commits/abbff06e6e02443c7b69d17d705b08ae62ad2ef5 and https://github.com/digitalcredentials/dcc-website-jekyll/pull/10/commits/c23030979af4eaa559157299b11915c0dbdba02f

**Comment by kayaelle** [comment]
Looks good!
