### ISSUE TITLE
Accessibility: Link to Last Mile Report

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#34]
- [x]  On the home page , Please add  " (PDF)" to the text in the link to the Last Mile Report 
- [x] On the Team Page, please add " (PDF)" to the link to Mozilla Open Badges" in Philipp's bio

**Comment by fields37** [comment]
Completed in https://github.com/digitalcredentials/dcc-website-jekyll/pull/7/commits/6180a0b21a95c8b216ec6db6ef652b29061140ac and https://github.com/digitalcredentials/dcc-website-jekyll/pull/7/commits/45d215d419e1d37d6682d37afd62665751ddd6aa. @kayaelle Do you want this added for the whitepaper link on the homepage as well?

**Comment by kayaelle** [comment]
@fields37 - yes please

**Comment by fields37** [comment]
> @fields37 - yes please

Done in https://github.com/digitalcredentials/dcc-website-jekyll/pull/7/commits/bd193d0ea035c0a356f65b6babc0f64dbb7d4032
