### ISSUE TITLE
Accessibility: Add description of images on Our Work 

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#35]
- [x] Please change the alt tag on the photo-1.jpg to "Photo of person wearing headphones using a laptop"
- [x] Please change the alt tag on the photo-2.jpg to "Photo of an institutional building"

**Comment by fields37** [comment]
Completed in https://github.com/digitalcredentials/dcc-website-jekyll/pull/7/commits/d6e9dd439109c8c7689986eff81c428c605f2636.

**Comment by kayaelle** [comment]
Looks great! Thanks @fields37 !
