### ISSUE TITLE
Accessibility: Team Page Link Color

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#37]
The Link color on this page is. a little lighter (007bff) than the links on other pages (0e6290).  Please  changethe links on the team page to: 0e6290

**Comment by fields37** [comment]
I realized that I had forgotten to put the team members section into the normal page-content div that regulates link colors in that section. @kayaelle do you want the social buttons in the team member bios to also switch to the slightly darker link color, or go back to the brighter blue?  Here is what the difference looks like:
<img width="367" alt="Screen Shot 2023-06-12 at 2 20 04 PM" src="https://github.com/digitalcredentials/dcc-website/assets/20584379/c21456e9-772
<img width="366" alt="Screen Shot 2023-06-12 at 2 20 17 PM" src="https://github.com/digitalcredentials/dcc-website/assets/20584379/496bb0c5-dd22-4056-9be3-bf16f1b9a0c5">
5-4c08-86f2-a38e53bc0333">

**Comment by kayaelle** [comment]
@fields37 - I prefer the darker icons too and that they match the link color. Thanks!
