### ISSUE TITLE
Minor Markup Fixes

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#40]
Please view notices here and make adjustments: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdigitalcredentials.github.io%2Fdcc-website-jekyll%2F

**Comment by fields37** [comment]
Completed in https://github.com/digitalcredentials/dcc-website-jekyll/pull/9

**Comment by kayaelle** [comment]
Nice work!
