### ISSUE TITLE
Update Team Bios

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#43]
Edit team bios with this text: https://docs.google.com/document/d/1Jn6mENMRmZ3Q-udCusdDoX8sHdBw833XZ4pkxOnIdhQ/edit

Please also add Kerri Linkedin (as hyperlink)

**Comment by fields37** [comment]
Also add bolding to team member names in bio

**Comment by fields37** [comment]
Completed in https://github.com/digitalcredentials/dcc-website-jekyll/commit/e8210e9bcf80d758b2b52354e466a275f9f217d2
