### ISSUE TITLE
Add Github icon with link to repos in footer

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#44]
Add Github icon and link to public repos: https://github.com/digitalcredentials

(Later: add icon to Linkedin page. We do not have this yet.)

**Comment by kayaelle** [comment]
@gwalsh311 - where in the footer should this go?

**Comment by kayaelle** [comment]
I'd rather not put it up there. 

I think we should hold off on adding this right now. We can go big and highlight our repo in the near future.
