### ISSUE TITLE
Who We are Members List & Membership Page

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#45]
- [x] Create notations for Core Members vs. Founding Members (Use an asterisk or other symbol to denote).  
- [x] Add "Western Governors University" with core notation (NOT founding member notation)
- [x] All other members should have both Core and Founding notations. 
- [x] On https://digitalcredentials.github.io/dcc-website-jekyll/membership
Please change:
Joining the Digital Credentials Consortium begins with a conversation, let’s talk!
to:
Joining the Digital Credentials Consortium begins with a conversation, please email us at dcc-membership-inquiry -at- mit -dot- edu.

- [x] on https://digitalcredentials.github.io/dcc-website-jekyll/get-involved
Change:
Institutional Members
To:
Institutions

**Comment by gwalsh311** [comment]
@fields37 Include key with the notations:

* denotes founding member
+ denotes core member

**Comment by fields37** [comment]
'*' for founding member
'†' for core member

**Comment by fields37** [comment]
Change to Get Involved page "Institutions" header made in https://github.com/digitalcredentials/dcc-website-jekyll/blob/master/get-involved.md

**Comment by fields37** [comment]
Changes to members section (founding/core member notation, addition of WGU) made in https://github.com/digitalcredentials/dcc-website-jekyll/commit/48e6ebcbbebbe57b5be9bb864f7369a82e6a669f

**Comment by kayaelle** [comment]
Looks great!
