### ISSUE TITLE
Change Publications Page to Resources

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#49]
- [x] Menu change from Publications to Resources
- [x] Page Header from Publications to Resources
- [x] Add H2 for Publications above the list of publications

**Comment by fields37** [comment]
Completed in https://github.com/digitalcredentials/dcc-website-jekyll/commit/ab8783bc5f6cd90903c90c1054aedba764a6b082

**Comment by kayaelle** [comment]
Looks good. Closing. Thanks!
