### ISSUE TITLE
Who We Are Page

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#5]
For page header, please use the background: https://digitalcredentials.mit.edu/images/bg-2.jpg

This is the same background use for the blurbs preceding each section on the current homepage. Same font style (white, centered, etc.) can be used for the "Who We Are" text.

Add subheaders for these sections:
- Current Members
- Benefits of Membership
- Join

and each section should have room for content. Ok to put some placeholder content in there for now.

For sub-header style, please use the style applied to H2 on the current site for subheaders like: "A University-Led Effort"

**Comment by kayaelle** [comment]
Question from @fields37 for @bmuramatsu & @gwalsh311:

Will the "Join" section in "Who we are" have a button, form, etc? Do we want to just have it look like the "Sign up for updates" section on the current site (image attached)?

**Comment by kayaelle** [comment]
I recommended that @fields37 copy the "sign Up" section from the homepage for now.

**Comment by fields37** [comment]
The draft version of this page can be viewed [here](https://digitalcredentials.github.io/dcc-website-jekyll/who-we-are), once we have content to fill in I can insert it.

**Comment by kayaelle** [comment]
Underneath list of current members, please add a section for Team. For each team member, there will be:

- Photo
- Name
- Title
- Link to LinkedIn or webpage
- Short bio (2-3 sentences)

**Comment by fields37** [comment]
Hey, I threw together an initial design for the team member entries you can view [here](https://digitalcredentials.github.io/dcc-website-jekyll/who-we-are). I added icons where a member can link to any linkedin, twitter, github, personal website, etc. Let me know what you think and I can change up the design however!

<img width="1451" alt="Screen Shot 2023-04-03 at 5 10 42 PM" src="https://user-images.githubusercontent.com/20584379/229628533-a060c460-a147-46d0-be75-a83580991d43.png">
<img width="447" alt="Screen Shot 2023-04-03 at 5 11 00 PM" src="https://user-images.githubusercontent.com/20584379/229628539-1d298521-6bf4-4219-b06f-26feefbb54c3.png">

**Comment by bmuramatsu** [comment]
Gabe/Gillian please drop the LinkedIn link for me. I don't publicize it. My
website https://mura.org yes. Thanks.

**Comment by fields37** [comment]
No problem Brandon, also if you'd like to change the bio text please let me know, I just pulled it from your Linkedin.

**Comment by fields37** [comment]
Hi Brandon, do you want the Team and Leadership Council member lists to include the same sort of entries as I made above for team members with photo, bio, and links, or should the info about each person be more stripped down?

**Comment by bmuramatsu** [comment]
If we do it, yes similar design but probably just photo, name, title.

But for the moment, don't display the Leadership Council entries. We're
still discussing if they should be listed.

**Comment by fields37** [comment]
[New rev](https://digitalcredentials.github.io/dcc-website-jekyll/who-we-are) of the "Who we are" page, I added the sections from your doc and tightened up the sizing of the team members display a tad.

**Comment by bmuramatsu** [comment]
I suggest you look at how much more prominent Team member names and titles
appear in contrast with paying consortium member names.

**Comment by gwalsh311** [comment]
@fields37 here we want to just have the member institutions as listed but more prominently if that makes sense. and then create a new page (with navigation tab at the top) for the team (this will include the team photos and bios).
