### ISSUE TITLE
Merge Who We Are & Team 

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#50]
- [x] Move this: :If you represent a higher education or post-graduate institution we invite you to [learn more about membership](https://digitalcredentials.github.io/dcc-website-jekyll/membership). out of call to action to a sentence below the list.
- [x] Add Team and Team bios below Member list
- [x] Change link at top of page "[team of professionals](https://digitalcredentials.github.io/dcc-website-jekyll/team)" to anchor link to Team below
- [x] Remove Team page from subnavigation of Who We are

**Comment by fields37** [comment]
I've reduced the size of the call to action a bit in https://github.com/digitalcredentials/dcc-website-jekyll/commit/0db905bbb4d2bc8eb99976b9838d4666181c5724, reviewable [here](https://digitalcredentials.github.io/dcc-website-jekyll/who-we-are)

**Comment by gwalsh311** [comment]
Looks good!
