### ISSUE TITLE
Add "Home" tab to nav bar

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#54]
Hi Gabe! Can you add a "Home" tab to the nav bar? Currently the only way to return to the landing page is to click the logo in the top left.

**Comment by fields37** [comment]
Completed in https://github.com/digitalcredentials/dcc-website-jekyll/pull/12/commits/1ed5b7ed421a6d775dc6c9d37e0f0d29eca57ae6, [review here](https://digitalcredentials.github.io/dcc-website-jekyll/)

**Comment by kayaelle** [comment]
Looks good
