### ISSUE TITLE
Edit text on "Who We Are"

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#55]
Change text to:

"Digital Credential Consortium members are non-profit or state-funded higher education or postgraduate education institutions from around the world on a mission to create a trusted, distributed, and shared infrastructure that will become the standard for issuing, storing, displaying, and verifying academic credentials, digitally.

The DCC is led by a Leadership Council elected by the DCC membership and is supported by a [team of professionals](https://digitalcredentials.github.io/dcc-website-jekyll/who-we-are#team)."

**Comment by kayaelle** [comment]
Looks good.
