### ISSUE TITLE
Add presentations to resources page

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#56]
@fields37 

Create header (same font/formatting as the "Presentations" header). Beneath include the following presentations with link to PDF (Do not link to Google drive). All of these have been ran through accessibility check and are available here: https://drive.google.com/drive/folders/12vB3UIGSFDjpmUqJPSwdTtBsUER-0p9Q

Include link to PDF below each citation. Thank you!

 
Muramatsu, B. (2022) Learner Credential Wallet [slide deck]. Moving Target Digitalisation Conference, Berlin, Germany.
2021 GDN,  

Muramatsu, B., van Valkenburg, W. (2021) Digital Credentials Enabling Mobility and Verification of Educational Achievements [slide deck]. Groningen Declaration Network, Ottawa, Canada. 

Hamilton Duffy, K., Lisle M., Muramatsu, B. (2021) Digital Credentials Consortium [slide deck]. IMS Digital Credentials Summit.

Muramatsu, B., Zagidulin, D. (2022) Digital Credentials Consortium: Learner Credential Wallet [slide deck]. July 7, 2022 DCC Community Call. 

Schmidt, J. P., (2022) Bridging the Last Mile: Credentials to Employment [slide deck]. AACRAO Technology and Transfer Summit.

**Comment by fields37** [comment]
Section added in https://github.com/digitalcredentials/dcc-website-jekyll/pull/12/commits/c1f94cf04d12df0f595816c11d35a3bd9bbbd2a2, can be reviewed [here](https://digitalcredentials.github.io/dcc-website-jekyll/resources). I wasn't sure exactly how you all wanted the citation formatting so let me know if there should be any changes. It also seems like [one of the presentations](https://drive.google.com/file/d/1JIRyqQjtgJmU3DWJzhyTFWStAn4TugZ1/view?usp=sharing) in the folder is missing a citation entry above, is this possibly the incomplete line I referenced in my previous comment?

**Comment by kayaelle** [comment]
@gwalsh311 please see above

**Comment by kayaelle** [comment]
We'll put the slides in /docs

**Comment by fields37** [comment]
Slides moved from external link to internal link in /docs/ in https://github.com/digitalcredentials/dcc-website-jekyll/commit/d8ff4b2b61819bfa09351bb7daffabfc65136181

**Comment by gwalsh311** [comment]
> 

Yes! Typo!

**Comment by gwalsh311** [comment]
Yes the "2021 GDN" is a typo. 
Sorry for the conclusion I have been working on the running the accessibility checks on these and adding to the folder as they are done. Will share the citations for all that are in the folder. 


Muramatsu, B., (2022) Learner Credential Wallet [slide deck]. March 2022 Verifiable Credentials for Education Task Force. 

Leu, S., Muramatsu, B., Murphy, S., Schmidt, J.P., (2022) Digital Credentials and the Last Mile to Employment [slide deck]. Open Learning Talks.

Lemoie, K., (2022) Digital Credentials Consortium Overview [slide deck]. InCommon Technical Advisory Committee Charter.

**Comment by fields37** [comment]
Ok I added these three presentations and corrected the citation language in https://github.com/digitalcredentials/dcc-website-jekyll/commit/f512ae66b977de749df67b16e2b024abc229f1c0

**Comment by gwalsh311** [comment]
Looks great! Will probably need to add a few more later.
