### ISSUE TITLE
Remove call out and membership inquiry form

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#58]
Please remove the entire bar containing the button that says Contact Us About Membership (thereby removing the link to the Google form). 

Replace dcc-membership-inquiry -at- mit -dot- edu with the actual email address dcc-membership-inquiry@mit.edu

**Comment by fields37** [comment]
Updated in https://github.com/digitalcredentials/dcc-website-jekyll/commit/cadda016ddc1e4d5c58fe7e4f085810e46a24ce4

**Comment by kayaelle** [comment]
Looks good.
