### ISSUE TITLE
Change text in Who We Are

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#59]
Change "Digital Credential Consortium members are non-profit or state-funded higher education or postgraduate education institutions from around the world on a mission to create a trusted, distributed, and shared infrastructure that will become the standard for issuing, storing, displaying, and verifying academic credentials, digitally.

The DCC is led by a Leadership Council elected by the DCC membership and is supported by a [team of professionals](https://digitalcredentials.github.io/dcc-website-jekyll/who-we-are#team)."

replace with:

Digital Credential Consortium members are non-profit or state-funded higher education or postgraduate education institutions from around the world. 

The DCC Mission: to create a trusted, distributed, and shared infrastructure that will become the standard for issuing, storing, displaying, and verifying academic credentials, digitally.

The DCC is led by a Leadership Council elected by the DCC membership and is supported by a [team of professionals](https://digitalcredentials.github.io/dcc-website-jekyll/who-we-are#team).

**Comment by fields37** [comment]
Updated in https://github.com/digitalcredentials/dcc-website-jekyll/commit/0ecda7c845e7276bdcdbb31a2a1683f8827fdaf4

**Comment by kayaelle** [comment]
Looks good
