### ISSUE TITLE
Technology Page

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#6]
For page header, please use the background: https://digitalcredentials.mit.edu/images/bg-2.jpg

This is the same background use for the blurbs preceding each section on the current homepage. Same font style (white, centered, etc.) can be used for the "Technology" text.

add the following sections with sub-headers:

- Standards Support 
- Verifiable Credentials / Open Badges v3
- Issuer
- Wallet (LCW and any wallets we recommend)
- Verifier (verify.dcconsortium.org and verifierplus.org)
- Registries
- Github Repo

and each section should have room for content. Ok to put some placeholder content in there for now.

For sub-header style, please use the style applied to H2 on the current site for subheaders like: "A University-Led Effort" (same as #5 )

**Comment by fields37** [comment]
The draft version of this page can be viewed [here](https://digitalcredentials.github.io/dcc-website-jekyll/technology)

**Comment by gwalsh311** [comment]
Hi Gabe - Can you add the content here to the technology page?[https://docs.google.com/document/d/1N6noeCAd-Q3mAfNen7V7iN8B8F9BpcrPhQODriWmaJM/edit#](url)
There is a bullet point for TECHNOLOGY

**Comment by fields37** [comment]
Hi Gillian, do you want this to be added to the existing content on the page, or replacing it?

**Comment by gwalsh311** [comment]
@fields37 Hi Gabe, actually we will be merging technology and projects on to one page and replacing it all. Can you look at the highlighted content here? https://docs.google.com/document/d/1N6noeCAd-Q3mAfNen7V7iN8B8F9BpcrPhQODriWmaJM/edit#heading=h.mgjnnyojj5wt Let me know if you have questions.
