### ISSUE TITLE
Edit footer

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#60]
Update copyright to ---  © 2023 MIT Open Learning

Update address in footer to 

MIT Open Learning
600 Technology Square
Cambridge, MA 02139

Massachusetts Institute of Technology

**Comment by fields37** [comment]
Updated in https://github.com/digitalcredentials/dcc-website-jekyll/commit/523f67159ab6796fd546618cb45a367c1b5f8ec2

**Comment by kayaelle** [comment]
Looks good.
