### ISSUE TITLE
Make changes to footer

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/dcc-website#67]
- [ ] Reinstate list of core members in the footer (like how it looked on the old site). You can see what it looked like here: https://web.archive.org/web/20230521020426/https://digitalcredentials.mit.edu/

**Founding Members**
Delft University of Technology (The Netherlands)
Georgia Tech (USA)
Harvard University (USA)
Hasso Plattner Institute, University of Potsdam (Germany)
Massachusetts Institute of Technology (USA)
McMaster University (Canada)
Tecnologico De Monterrey (Mexico)
TU Munich (Germany)
UC Berkeley (USA)
UC Irvine (USA)
University of Milano-Bicocca (Italy)
University of Toronto (Canada)

- [ ] update copyright in footer to (C) 2023 MIT

**Comment by fields37** [comment]
Hi, did you want the copyright to say MIT and not MIT Open Learning?

**Comment by kayaelle** [comment]
Hey @fields37 - yes please

**Comment by kayaelle** [comment]
@gwalsh311 - if this looks good to you. Please close the issue. Thanks!

**Comment by gwalsh311** [comment]
@kayaelle I deleted the MIT address altogether. It was already on the left side of the footer
