### ISSUE TITLE
Publications Page

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#8]
For page header, please use the background: https://digitalcredentials.mit.edu/images/bg-2.jpg

This is the same background use for the blurbs preceding each section on the current homepage. Same font style (white, centered, etc.) can be used for the "Publications" text.

The content of this page will contain a list of our publications in reverse chronological order & APA formatted.

@gwalsh311 will provide the final content. The list will be something like:

- Whitepaper (link to /docs/filename)
- Open Source Wallet Final Report (link to /docs/filename)
- Last Mile Report (link to /docs/filename)
- [ultimately Ecosystem Map & Report]
- (Presentations) (link to /docs/filename or PDF of Google slides for access control) - Community call for Open Badges in December - print as PDF and then test for accessibility (download as powerpoint, create PDF, and see what Acrobat says about accessibility, repeat and rinse)

**Comment by kayaelle** [comment]
Question from @fields37 for @bmuramatsu & @gwalsh311:

For the APA formatting on the publications section, do you want any special formatting or does that just refer to how the citation is written?

**Comment by kayaelle** [comment]
I recommended to @fields37  that the formatting will be APA. If other additional formatting is needed, we can file a new issue.

**Comment by fields37** [comment]
@kayaelle When we say the formatting will be APA, do we just mean we will have a plaintext list of publication names, with the citation written in APA format, e.g. "Student teachers who use technology in their lessons tend to continue using technology tools throughout their teaching careers (Kent & Giles, 2017, p. 12)."?

**Comment by fields37** [comment]
This conversation is being continued in Issue #9. @kayaelle I would suggest we close this issue to remove redundancy.

**Comment by kayaelle** [comment]
ok - will close this one. @bmuramatsu - please add the list of publications to #9 

Thanks
