### ISSUE TITLE
APA Formatting for Publications Page

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/dcc-website#9]
Please setup an unordered list with no bullet and a hanging indent that approximates the display like on this page: [Reference List: Author/Authors](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/reference_list_author_authors.html)

**Comment by kayaelle** [comment]
@fields37 - here is an APA 7 example of one of our reports: 

Camilleri, A.F.. Muramatsu, B., & Schmidt, P. (2022, September 30). _Credentials to Employment: The Last Mile_. https://digitalcredentials.mit.edu/docs/Credentials-to-Employment-The-Last-Mile.pdf

@bmuramatsu @gwalsh311 - please list all of the publications and related info needed for each one in this issue.

**Comment by fields37** [comment]
The current plan is to structure the list of publications as an object data structure defined in the front matter tags of the "publications" markdown page. This will allow you all to enter in publication title, author, link, etc as variables and have the italicization, bolding and underlining formatting handled by the html layout.

**Comment by bmuramatsu** [comment]
I strongly encourage you to structure the page as either plain HTML or a box that takes HTML and have the person adding the citation format the citation before publishing it.

As described, you're talking about rebuilding Citation Machine -- you would need to build a very flexible system to allow for the publication types we're likely to use. And you'd have to worry about sorting and a number of data structure issues.

If you want to build a system -- it would be better for us to use Wordpress and use a plugin to do it and the other functionality we need instead of a custom coded site.

**Comment by fields37** [comment]
That makes sense to me, I didn't realize the final formatting can wind up being so variable. Based on this, instead of going with my above suggestion, I will just leave it as an unordered list in markdown with italics and bolding manually arranged by the author.

**Comment by fields37** [comment]
I've implement this format in https://github.com/digitalcredentials/dcc-website-jekyll/commit/88afa9b841273539e6ba22622ca5792faeca9776. It can be previewed at https://digitalcredentials.github.io/dcc-website-jekyll/publications, and the source markdown can be viewed and edited at https://github.com/digitalcredentials/dcc-website-jekyll/blob/master/publications.md

**Comment by kayaelle** [comment]
Please add these two and remove those in there for testing:

Chartrand, J., Freeman, S., Gallersdörfer, U., Lisle, M., Mühle, van Engelenburg, S. (2018). Building the digital credential infrastructure for the future: A White Paper by the Digital Credentials Consortium. https://digitalcredentials.mit.edu/docs/white-paper-building-digital-credential-infrastructure-future.pdf

Hamilton Duffy, K., Gallersdörfer, U., Goodell, J., Lisle, M., Muramatsu, B., Schmidt, P. (2021, May). _Learner Credential Wallet Specification_. https://digitalcredentials.mit.edu/docs/Learner-Credential-Wallet-Specification-May-2021.pdf

**Comment by gwalsh311** [comment]
Hello in addition to what Kerri mentioned above please add these two:

Camilleri A, Muramatsu B. & Schmidt, P. (2022) Credentials to Employment: The Last Mile.
[](https://digitalcredentials.mit.edu/docs/Credentials-to-Employment-The-Last-Mile.pdf)

Schmidt, J.P., Muramatsu, B., Walsh, G. & Zagidulin D. (2022) [Open Source Student Wallet Final Report](https://digitalcredentials.mit.edu/docs/Open%20Source%20Student%20Wallet%20Final%20Report%20-%20Public%20Web%20Version.pdf)

**Comment by bmuramatsu** [comment]
Can we please attributed the whitepaper to the editors and not the contributing authors.

Hamilton Duffy, K., Pongratz, H., & Schmidt, J. P. (Eds.). (2018). _Building the digital credential infrastructure for the future: A White Paper by the Digital Credentials Consortium_. https://digitalcredentials.mit.edu/docs/white-paper-building-digital-credential-infrastructure-future.pdf

**Comment by fields37** [comment]
Hey Brandon, is [this](https://digitalcredentials.github.io/dcc-website-jekyll/publications) how you'd like the publication links to appear? I removed the bolding and black styling.

**Comment by bmuramatsu** [comment]
This is better, thanks.
