### ISSUE TITLE
Mission & Top Statement

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#95]
Wondering of we should put the mission back and then replace the top statement with the description about advancing.

**Comment by kayaelle** [comment]
Assigning to @LauraHilliger but not working oddly...

**Comment by LauraHilliger** [comment]
fixed this and it's working fine locally. Commit: https://github.com/digitalcredentials/dcc-website/commit/2c27c6b6390bdcdbdead11ec8c3f8e9de3cad10c

**Comment by kayaelle** [comment]
Hey @LauraHilliger - could you take a second look at this commit? It's not showing up as a PR and when I click on the commit link it says: This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by LauraHilliger** [comment]
Yep, ok I tried submitting a PR now – there's other commits, including reverts of those commits. Sorry @kayaelle I'm trash at githubbing! Here's the PR https://github.com/digitalcredentials/dcc-website/pull/99

**Comment by alexfigtree** [comment]
@LauraHilliger Your PR was merged, am now closing this ticket, thanks!
